env:
  serviceName: "cryp-kaspad"
  log:
    # level 可動態更新，無需重啟服務
    level: debug
    output: file
    outputs:
      file: ./logs/cryp_kaspad_log
      elasticsearch:
        - http://elasticsearch:9200
  debug: true
  port: 30000

pyroscope:
  isRunStart: true
  url: "http://127.0.0.1:4041"

db:
  gorm:
    logMode: warn
  master:
    host: mysql
    port: 3306
    username: root
    password: 1234
    name: db_cryp_kaspad
    maxIdleConns: 10
    maxOpenConns: 30
    connMaxLifetime: 30

node:
  url:
    - "10.34.0.108:16210"
    #- "https://kaspa.eosphere.io"
    #- "http://10.42.16.56:8888"
    #- "http://10.34.0.108:8888"
    #- "https://node2.eosphere.io"
    #- "https://api.eosrio.io"
  confirm: 12
  gasPrice: 1000000000
  #accountID: "shikanokopay"
  #privateKey: "5KPk1hg8vJgBXA4QqmtVDTwX6SXJoueYiLGSPhZPc7y1e3VNEnV"
  accountID: "shikanoko.gm"
  privateKey: "5KMHTN5mhAVRz71QvMcgZP4kEsm3bGo6JqkbMVg3kQDMK6oGseG"
  retry: 3
testNet:
  Enable: true
wallet:
  deposit:
    accountID: "kaspa:qpq76e7wgkvce6vepccwga9284l835epyl0lnfedhkfde4r03uqm6hrnxuwc5"
    privateKey: "affcb6bd3bfaf224b4f3ab2f016d5a8de44d3fd8928e1f9365bde3ad23d27c8d"
    publicKey: "41ed67ce45998ce9990e30e474aa3d7e78d32127dff9a72dbd92dcd46f8f01bd"

notify:
  opDevURL: "http://61.216.66.135:78"
  opPreURL: "http://pre-paymentpooltoken.1-pay.co"
  opURL: "http://paymentpooltoken.1-pay.co"
  qaURL: "http://mock.logintt.com"

goroutineSize:
  block: 10
  trans: 5
  db: 10


#quick buzz imitate change ethics speak